### PR TITLE
enable ignore ssl certificated when connecting to VIServer

### PR DESCRIPTION
**Pull request by circlelychen**
Hi @dannvix 

Sometimes, I would like to connect VIServer without certificate verification. 

Please help me review it

Thanks

### CODE REVIEW

**Comment by dannvix** [comment]
Hi @circlelychen,

Nice enhancement. However, I prefer adding a new method `VIVirtualMachine.send_ssl_no_verify()`, and the example could be:

```python
server = VIServer()
server.set_ssl_no_verify()
server.connect('10.1.0.1', 'username', 'passw0rd')
# ...
```

**Comment by dannvix** [comment]
By the way, @circlelychen, please don't push IP address and passwords in your `examples/list_vms_ignore_ssl_verify.py`. Thanks.

**Comment by circlelychen** [comment]
Thanks for your comments.  It is very useful and **important**.

**Comment by circlelychen** [comment]
Please take a look for updated one.

Thanks

**Comment by dannvix** [comment]
That's great, thank you.

However the `example/list_vms_ignore_ssl_verify.py` needs an update to comply with the new `set_ssl_no_verify()` API :-)

**Comment by circlelychen** [comment]
Please refer to commit [81cfce6](https://github.com/dannvix/pySphere/pull/9/commits/81cfce69a5d4ce2db3cc917816c041364c4dd79d)

**Comment by dannvix** [comment]
Awesome! 👍

**Pull request merged**
